include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_empty_else: true
    empty_statements: true
    unnecessary_new: true
    unnecessary_this: true
    avoid_print: false
    prefer_single_quotes: false
    camel_case_types: true