name: ecommerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  animations: ^2.0.8
  beamer: ^1.5.6
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  email_validator: ^2.1.17
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.3
  http_interceptor: ^2.0.0-beta.6
  provider: ^6.0.5
  synchronized: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/svgs/
